version: '3.7'
services:
  report-app:
    container_name: report-app
    restart: always
    command: tail -f /dev/null
    volumes:
      - ./report-app:/report-app
    build:
      context: report-app
      dockerfile: ./Dockerfile
    ports:
      - 8001:8001